version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace-api
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - marketplace-network

  mongodb:
    image: mongo:6.0
    container_name: marketplace-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env
    networks:
      - marketplace-network

networks:
  marketplace-network:
    driver: bridge

volumes:
  mongodb_data:
    name: marketplace-mongodb-data 